maps = {}

maps[0] = {
        #first row
        #'A1': None,
        #'A2': None,
        'A3': 'KC_TRANS',
        'A4': 'KC_TRANS',
        'A5': 'LCTL(KC_S)',# CTRL-S
        'A6': 'LCTL(KC_C)',
#        'A7': 'KC_TRANS',
#        'A8': 'KC_TRANS',
#        'A9': 'KC_TRANS',
#        'A10': 'KC_TRANS',
        'A11': 'LALT(KC_F4)',
        'A12': 'OSM(MOD_LCTL)',
        'A13': 'OSM(MOD_LALT)',
        'A14': 'OSM(MOD_LGUI)',
        #'A15': 'KC_TRANS',
        #'A16': 'KC_TRANS',

        'B1': 'KC_TRANS',
        'B2': 'KC_TRANS',
        'B3': 'KC_COMMA',
        'B4': 'KC_DOT',
        'B5': 'KC_P',
        'B6': 'KC_Y',
#        'B7': 'KC_TRANS',
#        'B8': 'KC_TRANS',
#        'B9': 'KC_TRANS',
#        'B10': 'KC_TRANS',
        'B11': 'KC_F',
        'B12': 'KC_G',
        'B13': 'KC_C',
        'B14': 'KC_R',
        'B15': 'KC_TRANS',
        'B16': 'KC_EQUAL',

        'C1': 'KC_TAB',
        'C2': 'KC_QUOTE',
        'C3': 'KC_O',
        'C4': 'KC_E',
        'C5': 'KC_U',
        'C6': 'KC_I',
#        'C7': 'KC_TRANS',
#        'C8': 'KC_TRANS',
#        'C9': 'KC_TRANS',
#        'C10': 'KC_TRANS',
        'C11': 'KC_D',
        'C12': 'KC_H',
        'C13': 'KC_T',
        'C14': 'KC_N',
        'C15': 'KC_L',
        'C16': 'KC_SLASH',

        'D1': 'KC_ESC',
        'D2': 'KC_A',
        'D3': 'KC_Q',
        'D4': 'KC_J',
        'D5': 'KC_K',
        'D6': 'KC_X',
#        'D7': 'KC_TRANS',
#        'D8': 'KC_TRANS',
#        'D9': 'KC_TRANS',
#        'D10': 'KC_TRANS',
        'D11': 'KC_B',
        'D12': 'KC_M',
        'D13': 'KC_W',
        'D14': 'KC_V',
        'D15': 'KC_S',
        'D16': 'KC_MINUS',

        'E1': 'KC_TRANS',
        'E2': 'KC_SCOLON', # actually, turn this arround, : before ;
        'E3': 'KC_TRANS',
        'E4': 'KC_TRANS',
        'E5': 'KC_TRANS',
        #'E6': 'KC_TRANS',
        'E7': 'KC_SPACE',
        'E8': 'KC_BSPACE',
        'E9': 'KC_DELETE',
        'E10': 'KC_ENTER',
        #'E11': 'KC_TRANS',
        'E12': 'KC_TRANS',
        'E13': 'KC_TRANS',
        'E14': 'KC_TRANS',
        'E15': 'KC_Z',
        'E16': 'KC_TRANS',

        'F4': 'KC_TRANS',
        'F6': 'KC_COPY',
        'F7': 'KC_PASTE',
        'F8': 'KC_TRANS',
        'F9': 'KC_TRANS',# layer shift
        'F10': 'KC_TRANS',# layer shift
        'F11': 'KC_TRANS',# layer shift
        'F13': 'KC_TRANS',

        'G7': 'KC_PGDOWN',
        'G8': 'KC_PGUP',
        'G9': 'KC_TRANS', # macro enter, change window, run last...
        'G10': 'KC_TRANS',


        }
maps['empty'] = {
        #first row
        #'A1': None,
        #'A2': None,
        'A3': 'KC_TRANS',
        'A4': 'KC_TRANS',
        'A5': 'KC_TRANS',# CTRL-S
        'A6': 'KC_TRANS',
#        'A7': 'KC_TRANS',
#        'A8': 'KC_TRANS',
#        'A9': 'KC_TRANS',
#        'A10': 'KC_TRANS',
        'A11': 'KC_TRANS',
        'A12': 'KC_TRANS',
        'A13': 'KC_TRANS',
        'A14': 'KC_TRANS',
        #'A15': 'KC_TRANS',
        #'A16': 'KC_TRANS',

        'B1': 'KC_TRANS',
        'B2': 'KC_TRANS',
        'B3': 'KC_TRANS',
        'B4': 'KC_TRANS',
        'B5': 'KC_TRANS',
        'B6': 'KC_TRANS',
#        'B7': 'KC_TRANS',
#        'B8': 'KC_TRANS',
#        'B9': 'KC_TRANS',
#        'B10': 'KC_TRANS',
        'B11': 'KC_TRANS',
        'B12': 'KC_TRANS',
        'B13': 'KC_TRANS',
        'B14': 'KC_TRANS',
        'B15': 'KC_TRANS',
        'B16': 'KC_TRANS',

        'C1': 'KC_TRANS',
        'C2': 'KC_TRANS',
        'C3': 'KC_TRANS',
        'C4': 'KC_TRANS',
        'C5': 'KC_TRANS',
        'C6': 'KC_TRANS',
#        'C7': 'KC_TRANS',
#        'C8': 'KC_TRANS',
#        'C9': 'KC_TRANS',
#        'C10': 'KC_TRANS',
        'C11': 'KC_TRANS',
        'C12': 'KC_TRANS',
        'C13': 'KC_TRANS',
        'C14': 'KC_TRANS',
        'C15': 'KC_TRANS',
        'C16': 'KC_TRANS',

        'D1': 'KC_TRANS',
        'D2': 'KC_TRANS',
        'D3': 'KC_TRANS',
        'D4': 'KC_TRANS',
        'D5': 'KC_TRANS',
        'D6': 'KC_TRANS',
#        'D7': 'KC_TRANS',
#        'D8': 'KC_TRANS',
#        'D9': 'KC_TRANS',
#        'D10': 'KC_TRANS',
        'D11': 'KC_TRANS',
        'D12': 'KC_TRANS',
        'D13': 'KC_TRANS',
        'D14': 'KC_TRANS',
        'D15': 'KC_TRANS',
        'D16': 'KC_TRANS',

        'E1': 'KC_TRANS',
        'E2': 'KC_TRANS', # actually, turn this arround, : before ;
        'E3': 'KC_TRANS',
        'E4': 'KC_TRANS',
        'E5': 'KC_TRANS',
        #'E6': 'KC_TRANS',
        'E7': 'KC_TRANS',
        'E8': 'KC_TRANS',
        'E9': 'KC_TRANS',
        'E10': 'KC_TRANS',
        #'E11': 'KC_TRANKC_TRANS',
        'E12': 'KC_TRANS',
        'E13': 'KC_TRANS',
        'E14': 'KC_TRANS',
        'E15': 'KC_TRANS',
        'E16': 'KC_TRANS',

        'F4': 'KC_TRANS',
        'F6': 'KC_TRANS',
        'F7': 'KC_TRANS',
        'F8': 'KC_TRANS',
        'F9': 'KC_TRANS',# layer shift
        'F10': 'KC_TRANS',# layer shift
        'F11': 'KC_TRANS',# layer shift
        'F13': 'KC_TRANS',

        'G7': 'KC_TRANS',
        'G8': 'KC_TRANS',
        'G9': 'KC_TRANS', # macro enter, change window, run last...
        'G10': 'KC_TRANS',


        }
